export const DEFAULT_WORKSPACE_CONTEXT_SCAN_INTERVAL_MINUTES = 5;
export const DEFAULT_WORKSPACE_CONTEXT_CLI_CONCURRENCY = 1;
export const DEFAULT_WORKSPACE_CONTEXT_MAINTENANCE_INTERVAL_HOURS = 24;
export const DEFAULT_WORKSPACE_CONTEXT_MAINTENANCE_CLI_CONCURRENCY = 1;
export const WORKSPACE_CONTEXT_DIRNAME = 'workspace-context';
export const WORKSPACE_CONTEXT_INSTRUCTION_FILENAME = 'WORKSPACE_CONTEXT.md';
export const WORKSPACE_CONTEXT_MANAGED_BLOCK_START = '<!-- AGENT_COCKPIT_WORKSPACE_CONTEXT_START -->';
export const WORKSPACE_CONTEXT_MANAGED_BLOCK_END = '<!-- AGENT_COCKPIT_WORKSPACE_CONTEXT_END -->';
