export const DEFAULT_CONTEXT_MAP_SCAN_INTERVAL_MINUTES = 5;
export const DEFAULT_CONTEXT_MAP_CLI_CONCURRENCY = 1;
export const DEFAULT_CONTEXT_MAP_EXTRACTION_CONCURRENCY = 3;
export const DEFAULT_CONTEXT_MAP_SYNTHESIS_CONCURRENCY = 3;
export const MAX_CONTEXT_MAP_PROCESSOR_CONCURRENCY = 6;
