// Regenerate docs/adr/README.md from ADR frontmatter.

const fs = require('fs');
const path = require('path');
const { parseFrontmatter } = require('./lib/adr-frontmatter');

const ADR_DIR = path.join(__dirname, '..', 'docs', 'adr');
const README = path.join(ADR_DIR, 'README.md');

function loadAdrs() {
  return fs.readdirSync(ADR_DIR)
    .filter(f => /^\d{4}-.+\.md$/.test(f))
    .sort()
    .map(file => {
      const content = fs.readFileSync(path.join(ADR_DIR, file), 'utf8');
      return { file, fm: parseFrontmatter(content) || {} };
    });
}

function row({ file, fm }) {
  const tags = Array.isArray(fm.tags) ? fm.tags.join(', ') : '';
  return `| [${fm.id}](${file}) | ${fm.status} | ${fm.date} | ${fm.title} | ${tags} |`;
}

function generate() {
  const adrs = loadAdrs();
  const rows = adrs.map(row).join('\n');
  return `# Architecture Decision Records

This directory contains Architecture Decision Records (ADRs) for Agent Cockpit.

ADRs capture *why* the system is shaped the way it is — the decision, the alternatives considered, and the tradeoffs accepted. SPEC documents (under \`docs/\`) describe *what is true now*. See [ADR-0001](0001-record-architecture-decisions.md) for the practice itself.

This file is auto-generated by \`scripts/adr-index.js\`. Do not edit manually — CI overwrites changes.

| ID | Status | Date | Title | Tags |
|----|--------|------|-------|------|
${rows}
`;
}

function main() {
  fs.writeFileSync(README, generate());
  console.log(`Wrote ${path.relative(process.cwd(), README)}`);
}

main();
