import type { ChildProcess } from 'child_process';
import type { CodexThreadGoal } from '../../types';
import { logger } from '../../utils/logger';
import { PROCESS_KILL_GRACE_MS } from './codexRuntime';

// The full protocol surface is generated by `codex app-server generate-ts`
// (see docs/spec-backend-services.md -> CodexAdapter). We hand-type only the
// shapes we actually use to keep the file small and avoid vendoring 400+
// generated files. Drift is checked manually by re-running the generator.

interface JsonRpcRequest {
  jsonrpc: '2.0';
  id: number;
  method: string;
  params?: Record<string, unknown>;
}

interface JsonRpcResponse {
  jsonrpc: '2.0';
  id?: number;
  result?: unknown;
  error?: { code: number; message: string; data?: unknown };
}

export interface JsonRpcNotification {
  jsonrpc: '2.0';
  method: string;
  params?: Record<string, unknown>;
  /** Present when the peer is sending a server-to-client request that needs a response. */
  id?: number;
}

type JsonRpcMessage = JsonRpcResponse | JsonRpcNotification;

export interface ThreadStartResult {
  thread: { id: string };
  model?: string;
}

export interface ThreadResumeResult {
  thread: { id: string };
}

export interface TurnStartResult {
  turn: { id: string; status?: string };
}

export interface ThreadGoalGetResult {
  goal: CodexThreadGoal | null;
}

export interface ThreadGoalSetResult {
  goal: CodexThreadGoal;
}

export interface ThreadGoalClearResult {
  cleared: boolean;
}

export interface ThreadReadResult {
  thread?: {
    status?: { type?: string };
    turns?: Array<{ id?: string; status?: string }>;
  };
}

// `item/tool/requestUserInput` (server-to-client request, EXPERIMENTAL,
// API v2 only). The server pauses the turn while waiting for our response.
export interface ToolRequestUserInputOption {
  label: string;
  description: string;
}

export interface ToolRequestUserInputQuestion {
  id: string;
  header: string;
  question: string;
  isOther?: boolean;
  isSecret?: boolean;
  options?: ToolRequestUserInputOption[];
}

export interface ToolRequestUserInputParams {
  threadId: string;
  turnId: string;
  itemId: string;
  questions: ToolRequestUserInputQuestion[];
}

// Each answer is a wrapping object holding a Vec<String> - multi-select capable.
interface ToolRequestUserInputAnswer {
  answers: string[];
}

export interface ToolRequestUserInputResponse {
  answers: Record<string, ToolRequestUserInputAnswer>;
}

export interface PendingUserInput {
  reqId: number;
  itemId: string;
  turnId: string;
  questions: ToolRequestUserInputQuestion[];
}

const codexProtocolLog = logger.child({ module: 'codex-protocol' });

export class CodexAppServerClient {
  private proc: ChildProcess;
  private nextId = 1;
  private pendingRequests: Map<number, { resolve: (value: unknown) => void; reject: (err: Error) => void }> = new Map();
  private notificationQueue: JsonRpcNotification[] = [];
  private notificationResolve: (() => void) | null = null;
  private buffer = '';
  private closed = false;
  private stopRequested = false;

  constructor(proc: ChildProcess) {
    this.proc = proc;
    if (typeof proc.stdin?.on === 'function') {
      proc.stdin.on('error', (err: Error) => {
        this.closeWithError(new Error(`Codex app-server stdin failed: ${err.message}`));
      });
    }

    proc.stdout!.on('data', (chunk: Buffer) => {
      this.buffer += chunk.toString();
      const lines = this.buffer.split('\n');
      this.buffer = lines.pop()!;

      for (const line of lines) {
        if (!line.trim()) continue;
        try {
          const msg = JSON.parse(line) as JsonRpcMessage;
          if ('method' in msg && msg.method) {
            // Notification or server-to-client request - both go through
            // the queue; the consumer distinguishes by the presence of `id`.
            this.notificationQueue.push(msg);
            if (this.notificationResolve) {
              this.notificationResolve();
              this.notificationResolve = null;
            }
          } else if ('id' in msg && msg.id != null) {
            const pending = this.pendingRequests.get(msg.id);
            if (pending) {
              this.pendingRequests.delete(msg.id);
              const resp = msg as JsonRpcResponse;
              if (resp.error) {
                pending.reject(new Error(resp.error.message));
              } else {
                pending.resolve(resp.result);
              }
            }
          }
        } catch {
          codexProtocolLog.warn('Failed to parse app-server message', {
            line: line.substring(0, 200),
          });
        }
      }
    });

    proc.on('close', () => {
      this.closeWithError(new Error('Codex app-server closed'));
    });
  }

  get isClosed(): boolean {
    return this.closed;
  }

  async request(method: string, params?: Record<string, unknown>): Promise<unknown> {
    if (this.closed) throw new Error('Codex app-server is closed');

    const id = this.nextId++;
    const msg: JsonRpcRequest = { jsonrpc: '2.0', id, method, ...(params !== undefined ? { params } : {}) };

    return new Promise((resolve, reject) => {
      this.pendingRequests.set(id, { resolve, reject });
      this.writeJson(msg);
    });
  }

  notify(method: string, params?: Record<string, unknown>): void {
    if (this.closed) return;
    const msg = { jsonrpc: '2.0', method, ...(params !== undefined ? { params } : {}) };
    this.writeJson(msg);
  }

  respond(id: number, result: unknown): void {
    if (this.closed) return;
    const msg = { jsonrpc: '2.0', id, result };
    this.writeJson(msg);
  }

  respondError(id: number, code: number, message: string): void {
    if (this.closed) return;
    const msg = { jsonrpc: '2.0', id, error: { code, message } };
    this.writeJson(msg);
  }

  private writeJson(msg: object): void {
    if (this.closed) return;
    const stdin = this.proc.stdin;
    if (!stdin || stdin.destroyed === true || stdin.writable === false) {
      this.closeWithError(new Error('Codex app-server stdin is closed'));
      return;
    }
    try {
      stdin.write(JSON.stringify(msg) + '\n');
    } catch (err: unknown) {
      this.closeWithError(new Error(`Codex app-server stdin failed: ${(err as Error).message}`));
    }
  }

  private closeWithError(err: Error): void {
    if (this.closed) return;
    this.closed = true;
    for (const [, pending] of this.pendingRequests) {
      pending.reject(err);
    }
    this.pendingRequests.clear();
    if (this.notificationResolve) {
      this.notificationResolve();
      this.notificationResolve = null;
    }
  }

  stopNotifications(): void {
    this.stopRequested = true;
    if (this.notificationResolve) {
      this.notificationResolve();
      this.notificationResolve = null;
    }
  }

  async *notifications(): AsyncGenerator<JsonRpcNotification> {
    while (!this.closed && !this.stopRequested) {
      if (this.notificationQueue.length > 0) {
        yield this.notificationQueue.shift()!;
      } else {
        await new Promise<void>((resolve) => {
          this.notificationResolve = resolve;
          setTimeout(resolve, 100);
        });
      }
    }
    while (this.notificationQueue.length > 0) {
      yield this.notificationQueue.shift()!;
    }
    this.stopRequested = false;
  }

  drainNotifications(onDrain?: (notification: JsonRpcNotification) => void): number {
    const drained = this.notificationQueue;
    this.notificationQueue = [];
    for (const notification of drained) {
      onDrain?.(notification);
    }
    const count = drained.length;
    return count;
  }

  kill(): void {
    if (!this.closed) {
      this.proc.kill('SIGTERM');
      // Hard kill if it doesn't shut down cleanly
      setTimeout(() => {
        if (!this.closed && !this.proc.killed) {
          this.proc.kill('SIGKILL');
        }
      }, PROCESS_KILL_GRACE_MS);
    }
  }
}

export function respondToStaleCodexRequest(
  client: CodexAppServerClient,
  notification: JsonRpcNotification,
  reason: string,
): boolean {
  if (notification.id == null) return false;
  const reqId = notification.id;
  switch (notification.method) {
    case 'item/commandExecution/requestApproval':
    case 'item/fileChange/requestApproval':
      client.respond(reqId, { decision: 'cancel' });
      return true;
    case 'item/permissions/requestApproval':
    case 'item/tool/requestUserInput':
      client.respondError(reqId, -32000, reason);
      return true;
    case 'applyPatchApproval':
    case 'execCommandApproval':
      client.respond(reqId, { decision: 'abort' });
      return true;
    default:
      client.respondError(reqId, -32601, 'Not supported by client');
      return true;
  }
}
